const COUNTRIES = {
  mne: { name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}' },
  usa: { name: 'United States', flag: '\u{1F1FA}\u{1F1F8}' },
  gbr: { name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}' },
  deu: { name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}' },
  fra: { name: 'France', flag: '\u{1F922}' },
  ita: { name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}' },
  esp: { name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}' },
  nld: { name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}' },
  srb: { name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}' },
  hrv: { name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}' },
  bih: { name: 'Bosnia & Herzegovina', flag: '\u{1F1E7}\u{1F1E6}' },
  aut: { name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}' },
  che: { name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}' },
  pol: { name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}' },
  can: { name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}' },
  aus: { name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}' },
  irl: { name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}' },
  swe: { name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}' },
  nor: { name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}' },
  dnk: { name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}' },
  bel: { name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}' },
  cze: { name: 'Czech Republic', flag: '\u{1F1E8}\u{1F1FF}' },
  hun: { name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}' },
  rou: { name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}' },
  bgr: { name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}' },
  grc: { name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}' },
  tur: { name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}' },
  rus: { name: 'Russia', flag: '\u{1F1F7}\u{1F1FA}' },
  ind: { name: 'India', flag: '\u{1F1EE}\u{1F1F3}' },
  jpn: { name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}' },
  bra: { name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}' },
  mkd: { name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}' },
  svn: { name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}' },
  svk: { name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}' },
  alb: { name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}' },
  prt: { name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}' },
  fin: { name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}' },
  isr: { name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}' },
  nzl: { name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}' },
  sgp: { name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}' },
  are: { name: 'UAE', flag: '\u{1F1E6}\u{1F1EA}' },
  zaf: { name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}' },
  ukr: { name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}' },
  ltu: { name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}' },
  lva: { name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}' },
  est: { name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}' },
  arg: { name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}' },
  mex: { name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}' },
  col: { name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}' },
  chl: { name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}' },
  per: { name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}' },
  tha: { name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}' },
  phl: { name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}' },
  mys: { name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}' },
  idn: { name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}' },
  kor: { name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}' },
  chn: { name: 'China', flag: '\u{1F1E8}\u{1F1F3}' },
  hkg: { name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}' },
  twn: { name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}' },
  egy: { name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}' },
  nga: { name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}' },
  ken: { name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}' },
};

export function getCountryInfo(code) {
  const c = COUNTRIES[code?.toLowerCase()];
  if (c) return c;
  // Try uppercase 2-letter to 3-letter conversion isn't needed — just return code
  return { name: code || 'Unknown', flag: '' };
}
