// Backend agent that applies a content rewrite (e.g., meta description,
// subtitle, title) by updating the relevant i18n key across all 7 locale
// JSONs and opening a PR for review.
//
// Zero runtime API tokens — uses pre-written content from contentRewrites.js.

import { Octokit } from '@octokit/rest';
import { REWRITES, LOCALES, getRewrite } from './contentRewrites.js';

const SITE_REPOS = {
  montenegrocarhire: { owner: 'pixelpowder', repo: 'montenegro-car-hire', defaultBranch: 'master' },
};

function octokit() {
  const token = process.env.GITHUB_TOKEN?.trim();
  if (!token) throw new Error('GITHUB_TOKEN env var not set');
  return new Octokit({ auth: token });
}

async function getFile(gh, owner, repo, path, ref) {
  const { data } = await gh.repos.getContent({ owner, repo, path, ref });
  if (Array.isArray(data) || data.type !== 'file') throw new Error(`${path} is not a file`);
  return { sha: data.sha, content: Buffer.from(data.content, 'base64').toString('utf8') };
}

async function putFile(gh, owner, repo, path, branch, content, sha, message) {
  await gh.repos.createOrUpdateFileContents({
    owner, repo, path, branch, message,
    content: Buffer.from(content, 'utf8').toString('base64'),
    sha,
  });
}

// Set a nested key like "podgorica-airport.seoDesc" on an object
function setKey(obj, dottedKey, value) {
  const parts = dottedKey.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (typeof cur[parts[i]] !== 'object' || cur[parts[i]] == null) cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = value;
}

function getKey(obj, dottedKey) {
  const parts = dottedKey.split('.');
  let cur = obj;
  for (const p of parts) {
    if (cur == null) return undefined;
    cur = cur[p];
  }
  return cur;
}

export async function implementContentRewrite({ siteId, page, contentType }) {
  const repoCfg = SITE_REPOS[siteId];
  if (!repoCfg) throw new Error(`No repo configured for siteId ${siteId}`);

  const rewrite = getRewrite(page, contentType);
  if (!rewrite) throw new Error(`No rewrite registered for ${page} / ${contentType}`);

  const { owner, repo, defaultBranch } = repoCfg;
  const gh = octokit();
  const slug = (s) => s.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase();
  const branch = `seo/rewrite-${slug(page)}-${contentType}`;

  // Branch off default
  const { data: refData } = await gh.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
  const baseSha = refData.object.sha;
  try { await gh.git.deleteRef({ owner, repo, ref: `heads/${branch}` }); } catch { /* didn't exist */ }
  await gh.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha });

  const beforeAfter = {}; // for PR body
  for (const loc of LOCALES) {
    const path = `src/i18n/locales/${loc}.json`;
    const { sha, content } = await getFile(gh, owner, repo, path, branch);
    const data = JSON.parse(content);
    const before = getKey(data, rewrite.i18nKey);
    const after = rewrite.content[loc] || rewrite.content.en;
    setKey(data, rewrite.i18nKey, after);
    beforeAfter[loc] = { before, after };
    const updated = JSON.stringify(data, null, 2) + '\n';
    await putFile(gh, owner, repo, path, branch, updated, sha,
      `i18n(${loc}): rewrite ${rewrite.i18nKey} for ${page}`);
  }

  // PR
  const pr = await gh.pulls.create({
    owner, repo, head: branch, base: defaultBranch,
    title: `SEO: rewrite ${contentType} for ${page}`,
    body: [
      `Auto-generated by carcam Internal Links agent.`,
      ``,
      `**Page:** \`${page}\``,
      `**Content type:** ${contentType}`,
      `**i18n key:** \`${rewrite.i18nKey}\``,
      ``,
      `## Before / after`,
      ``,
      ...LOCALES.map(loc => `**${loc.toUpperCase()}**\n- before: ${JSON.stringify(beforeAfter[loc].before)}\n- after: ${JSON.stringify(beforeAfter[loc].after)}\n`),
      `Review prose for natural reading + length (meta descriptions ~150-160 chars). Edit on this branch before merging if needed.`,
    ].join('\n'),
  });

  return { prUrl: pr.data.html_url, branch, prNumber: pr.data.number, beforeAfter };
}
